export const AUTHORIZE = 'AUTHORIZE';
export const AUTHORIZE_FAIL = 'AUTHORIZE_FAIL';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
